#!/usr/bin/env node

const {Client} = require('../dist/src');

const program = require('commander');

const client = new Client();


program
    .command('address')
    .option('-i, --init')
    .option('-s, --show')
    .option('-gb, --get_balance')
    .action(async (options) => {
        await client.init();
        if (options.show) {
            let a = await client.getAddress();
            console.log(a);
        }
        if (options.get_balance) {
            let a = await client.getBalance();
            console.log(a);
        }
    });

program
    .command('balance')
    .option('-ce, --ceth')
    .option('-cd, --cdai')
    .action(async (options) => {
        await client.init();
        if (options.ceth) {
            console.log("Checking for balance of cETH");
            let balance = await client.getBalanceCETH();
            console.log(balance);
        }
        if (options.cdai) {
            console.log("Checking for balance of cDAI");
            let balance = await client.getBalanceCDAI();
            console.log(balance);
        }
    });

program.parse(process.argv);
