#!/usr/bin/env node

const {Client} = require('../dist/src');
const {getAPR, getContractAPR} = require('../dist/src')

const program = require('commander');

const client = new Client();


program
    .command('address')
    .option('-i, --init')
    .option('-s, --show')
    .action(async (options) => {
        await client.init();
        if (options.show) {
            let a = await client.getAddress();
            console.log(a);
        }
    });

program
    .command('balance <symbol>')
    .action(async (symbol) => {
        await client.init();
        if (symbol === "ceth") {
            let balance = await client.getBalanceCETH();
            console.log(balance);
        }
        if (symbol === "cdai") {
            let balance = await client.getBalanceCDAI();
            console.log(balance);
        }
        if (symbol === "cusdc") {
            let balance = await client.getBalanceCUSDC();
            console.log(balance);
        }
        if (symbol == "eth") {
            let balance = await client.getBalanceETH();
            console.log(balance);
        }
        if (symbol == "dai") {
            let balance = await client.getBalanceDAI();
            console.log(balance);
        }
        if (symbol == "rep") {
            let balance = await client.getBalanceREP();
            console.log(balance);
        }
        if (symbol == "crep") {
            let balance = await client.getBalanceCREP();
            console.log(balance);
        }
        if (symbol == "usdc") {
            let balance = await client.getBalanceUSDC();
            console.log(balance);
        }
    });

program
    .command('apr <symbol>')
    .action(async (symbol) => {
        let apr = await getAPR(symbol);
        apr_num = Number(apr) * 100;
        console.log (parseFloat(Math.round(apr_num * 100) / 100).toFixed(2) + "%")
    });

program
    .command('capr <symbol>')
    .action(async (symbol) => {
        let apr = await getContractAPR(symbol);
        apr_num = Number(apr) * 100;
        console.log (parseFloat(Math.round(apr_num * 100) / 100).toFixed(2) + "%")
    });

program
    .command('mint <symbol> <amount>')
    .action(async (symbol, amount) => {
        await client.init();
        if (symbol === "ceth") {
            client.mintCETH(amount)
        }
        if (symbol === "cdai") {
            client.mintCDAI(amount)
        }
        if (symbol === "cusdc") {
            client.mintCUSDC(amount)
        }
        if (symbol === "crep") {
            client.mintCREP(amount)
        }
    });

program
    .command('estimate <symbol> <amount>')
    .action(async (symbol, amount) => {
        await client.init();
        if (symbol === "ceth") {
            client.estimateCETH(amount)
        }
        if (symbol === "cdai") {
            client.estimateCDAI(amount)
        }
        if (symbol === "cusdc") {
            client.estimateCUSDC(amount)
        }
        if (symbol === "crep") {
            client.estimateCREP(amount)
        }
    });

program
    .command('redeem <symbol> <amount>')
    .action(async (symbol, amount) => {
        await client.init();
        if (symbol === "ceth") {
            client.redeemCETH(amount)
        }
        if (symbol === "cdai") {
            client.redeemCDAI(amount)
        }
        if (symbol === "cusdc") {
            client.redeemCUSDC(amount)
        }
        if (symbol === "crep") {
            client.redeemCREP(amount)
        }
    });


program
    .command('approve <symbol> <amount>')
    .action(async (symbol, amount) => {
        await client.init();
        if (symbol === 'cdai') {
            console.log("Approve DAI");
            await client.approveCDAI(amount);
        }
        if (symbol === 'cusdc') {
            console.log("Approve CUSDC");
            await client.approveCUSDC(amount);
        }
        if (symbol === 'crep') {
            console.log("Approve CREP");
            await client.approveCREP(amount);
        }
    });

program
    .command('enter')
    .action(async (options) => {
        await client.init();
        await client.enterMarkets();
    });

program.parse(process.argv);
